r"""Corpus-derived prop-family placement recipes for tier-6 PROP groups.

Mined from the 12 professionally hand-built reference packages (.xsqz) in
``F:\ShowFolderAI`` — see ``docs/snowflake_sequencing_corpus/`` and
``docs/arch_sequencing_corpus/``, generated by ``scripts/mine_prop_corpus.py``:

- **Snowflakes** — dominant group effect is Shockwave (66% of 3.4k group
  placements; SingleStrand 28%), solid white (93% white-base), one placement
  per beat (median 0.97 beats in the strongest exemplars, 0.5-1 beat
  corpus-wide), concentrated in choruses/high-energy passages.
  ``Gone Gone Gone`` alternates Ripple/Shockwave between sections.
- **Arches** — solid-white Single Strand chase, one segment per beat,
  chorus/outro-confined, optionally recolored by a mask layer (not replicated
  here in v1).
- **Mega trees** — Shockwave bursts (36% of tree-proper placements, same
  center-out preset as snowflakes) alternating with sustained single-spiral
  Spirals spins (18%), solid white dominant. See
  ``docs/megatree_sequencing_corpus/``.

Snowflake and arch groups additionally carry a section-spanning **Off
backdrop** on the xLights layer beneath the bursts (``off_backdrop``): the
reference packages tile qualifying sections with 12-15s Off blocks on layer
index 1-2 of the group element so the props stay black between bursts.

A recipe only fires on qualifying sections (chorus-like label or high energy);
everywhere else the normal rotation/pool placement applies, so verses keep
today's behavior.

Matching is by name token on the tier-6 group name (``06_PROP_Snowflake``) or,
failing that, on a majority of member model names. Token matching is
substring-based ("arch" also matches "Arches"); tokens are chosen to be
distinctive within typical xLights prop naming.
"""

from __future__ import annotations

from dataclasses import dataclass

from src.generator.models import SectionEnergy
from src.grouper.grouper import PowerGroup


@dataclass(frozen=True)
class PropFamilyRecipe:
    """How a prop family is idiomatically sequenced, per the mined corpus."""

    family: str
    match_tokens: tuple[str, ...]
    effect_name: str
    # Alternate effect used on repeated sections (variation_seed odd) so
    # repeats vary, mirroring the Ripple/Shockwave alternation seen in the
    # corpus. None → always effect_name.
    alt_effect_name: str | None = None
    palette: tuple[str, ...] = ("#FFFFFF",)
    qualifying_labels: tuple[str, ...] = ("chorus", "drop", "hook", "climax", "build_peak")
    min_energy: int = 65
    # xLights parameter presets mined from the corpus placements. The primary
    # preset applies to effect_name; the alt preset applies to alt_effect_name
    # (empty → the alternate keeps library defaults).
    parameter_overrides: tuple[tuple[str, str], ...] = ()
    alt_parameter_overrides: tuple[tuple[str, str], ...] = ()
    # The reference packages place a section-spanning Off effect on the layer
    # beneath the beat bursts (xLights layer 2) on the group element, so the
    # props render black between bursts instead of picking up whole-house
    # bleed. Mined: snowflake Off placements are 43/58 on layer index 1;
    # arch 69/75 on layer index 1-2, spans of 12-15s tiling the sections.
    off_backdrop: bool = False


# Mined presets — near-unanimous across all 12 reference packages:
#
# SingleStrand chase (3.5k/4.9k placements use From Head; Color_Mix1 is the
# only per-song variable, 10-50, median 25): head-bright chase with a fading
# tail, the signature "comet" look of the reference shows.
_CHASE_FROM_HEAD: tuple[tuple[str, str], ...] = (
    ("E_NOTEBOOK_SSEFFECT_TYPE", "Chase"),
    ("E_CHOICE_Chase_Type1", "Left-Right"),
    ("E_CHOICE_Fade_Type", "From Head"),
    ("E_CHOICE_SingleStrand_Colors", "Palette"),
    ("E_SLIDER_Color_Mix1", "25"),
    ("E_SLIDER_Number_Chases", "1"),
)

# Shockwave burst (2.9k placements, fields >98% identical): center-out
# expanding ring, blended edges, single cycle.
_SHOCKWAVE_BURST: tuple[tuple[str, str], ...] = (
    ("E_NOTEBOOK_Shockwave", "Position"),
    ("E_CHECKBOX_Shockwave_Blend_Edges", "1"),
    ("E_CHECKBOX_Shockwave_Scale", "1"),
    ("E_SLIDER_Shockwave_Accel", "0"),
    ("E_SLIDER_Shockwave_CenterX", "50"),
    ("E_SLIDER_Shockwave_CenterY", "50"),
    ("E_SLIDER_Shockwave_Cycles", "1"),
    ("E_SLIDER_Shockwave_Start_Radius", "1"),
    ("E_SLIDER_Shockwave_Start_Width", "5"),
    ("E_SLIDER_Shockwave_End_Radius", "100"),
    ("E_SLIDER_Shockwave_End_Width", "35"),
)


# Megatree Spirals preset — mined from 720 Spirals placements on Mega Tree
# elements: single spiral (Count=1 at 96%), no grow/shrink (96-97%), blend
# off (87%); rotation/movement/thickness vary per song, so representative
# mid-corpus values are used.
_SPIRALS_MEGATREE: tuple[tuple[str, str], ...] = (
    ("E_SLIDER_Spirals_Count", "1"),
    ("E_SLIDER_Spirals_Rotation", "140"),
    ("E_SLIDER_Spirals_Thickness", "30"),
    ("E_TEXTCTRL_Spirals_Movement", "4"),
    ("E_CHECKBOX_Spirals_3D", "1"),
    ("E_CHECKBOX_Spirals_Blend", "0"),
    ("E_CHECKBOX_Spirals_Grow", "0"),
    ("E_CHECKBOX_Spirals_Shrink", "0"),
)


CORPUS_RECIPES: tuple[PropFamilyRecipe, ...] = (
    PropFamilyRecipe(
        family="snowflake",
        match_tokens=("snowflake", "flake"),
        effect_name="Shockwave",
        alt_effect_name="Ripple",
        parameter_overrides=_SHOCKWAVE_BURST,
        off_backdrop=True,
    ),
    PropFamilyRecipe(
        family="arch",
        match_tokens=("arch",),
        effect_name="Single Strand",
        parameter_overrides=_CHASE_FROM_HEAD,
        off_backdrop=True,
    ),
    # Mega tree — mined from the same 12 packages (docs/megatree_sequencing_
    # corpus/): tree-proper placements are Shockwave 36% (same center-out
    # burst preset as snowflakes, >96% Blend_Edges/Cycles=1/Start_Width=5),
    # Spirals 18% (sustained ~2-beat spins), 93%+ solid single-color white.
    # Off backdrop is NOT part of the megatree idiom (55/7.7k placements).
    # Tokens match "06_PROP_Mega_Tree" and member names like "Mega Tree 2";
    # "Mega Topper" props deliberately do not match — different prop family.
    PropFamilyRecipe(
        family="megatree",
        match_tokens=("megatree", "mega_tree", "mega tree"),
        effect_name="Shockwave",
        alt_effect_name="Spirals",
        parameter_overrides=_SHOCKWAVE_BURST,
        alt_parameter_overrides=_SPIRALS_MEGATREE,
    ),
)


def recipe_for_group(group: PowerGroup) -> PropFamilyRecipe | None:
    """Return the corpus recipe for a tier-6 PROP group, or None.

    Radial sub-groups (``prop_type == "radial"``) are never matched — they
    already have a dedicated chase-across-members placer that the corpus
    recipe must not displace.
    """
    if group.tier != 6 or group.prop_type == "radial":
        return None
    name = group.name.lower()
    for recipe in CORPUS_RECIPES:
        if any(token in name for token in recipe.match_tokens):
            return recipe
    if group.members:
        for recipe in CORPUS_RECIPES:
            hits = sum(
                1 for member in group.members
                if any(token in member.lower() for token in recipe.match_tokens)
            )
            if hits / len(group.members) > 0.5:
                return recipe
    return None


def section_qualifies(recipe: PropFamilyRecipe, section: SectionEnergy) -> bool:
    """Corpus recipes fire on chorus-like sections or high-energy passages."""
    label = (section.label or "").lower()
    if any(keyword in label for keyword in recipe.qualifying_labels):
        return True
    return section.energy_score >= recipe.min_energy
