r"""Corpus-derived prop-family placement recipes for tier-6 PROP groups.

Mined from 12 professionally hand-built reference packages (.xsqz) in a
local corpus folder (never committed) — see ``docs/snowflake_sequencing_corpus/``
and ``docs/arch_sequencing_corpus/``, generated by ``scripts/mine_prop_corpus.py``:

- **Snowflakes** — dominant group effect is Shockwave (66% of 3.4k group
  placements; SingleStrand 28%), solid white (93% white-base), one placement
  per beat (median 0.97 beats in the strongest exemplars, 0.5-1 beat
  corpus-wide), concentrated in choruses/high-energy passages.
  One corpus song alternates Ripple/Shockwave between sections.
- **Arches** — solid-white Single Strand chase, one segment per beat,
  chorus/outro-confined, optionally recolored by a mask layer (not replicated
  here in v1).
- **Mega trees** — Shockwave bursts (36% of tree-proper placements, same
  center-out preset as snowflakes) alternating with sustained single-spiral
  Spirals spins (18%), solid white dominant. See
  ``docs/megatree_sequencing_corpus/``.
- **Candy canes** — white SingleStrand chase (45% of 3.0k placements,
  ~half-beat segments) alternating with flat 2D Spirals (24%, ~one beat),
  colored by a section-spanning On layer with "2 is Unmask" over the motion
  effect (the mega-tree ``color_over_mask`` idiom; 459/467 On placements).
  See ``docs/cane_sequencing_corpus/``.
- **Matrices** — three layers deep: On "2 is Unmask" color over per-beat
  white Shockwave bursts (alt: mined Pinwheel) over a sustained Spirals
  spin, mirroring the corpus's multi-layer matrix stacks.
  See ``docs/matrix_sequencing_corpus/``.
- **Mini trees** — white Right-Left SingleStrand chase across the tree group
  (73% of 7.2k placements, ~0.6-beat segments), colored by the same
  On "2 is Unmask" layer, alternating with white Shockwave bursts.
  See ``docs/minitree_sequencing_corpus/``.
- **Horizontal / vertical lines** — white From-Head SingleStrand chase, one
  segment per beat (70%/66% of 1.6k/1.8k placements, 85-89% From Head),
  colored by the same On "2 is Unmask" layer (100% of On placements in both
  families), with white Lightning flickers as the recurring alternate
  (11%/18%, one unanimous preset). See
  ``docs/horizontal_sequencing_corpus/`` and
  ``docs/vertical_sequencing_corpus/``.

Snowflake and arch groups additionally carry a section-spanning **Off
backdrop** on the xLights layer beneath the bursts (``off_backdrop``): the
reference packages tile qualifying sections with 12-15s Off blocks on layer
index 1-2 of the group element so the props stay black between bursts.

A recipe only fires on qualifying sections (chorus-like label or high energy);
everywhere else the normal rotation/pool placement applies, so verses keep
today's behavior.

Matching is by name token on the tier-6 group name (``06_PROP_Snowflake``) or,
failing that, on a majority of member model names. Token matching is
substring-based ("arch" also matches "Arches"); tokens are chosen to be
distinctive within typical xLights prop naming.
"""

from __future__ import annotations

from dataclasses import dataclass

from src.generator.models import SectionEnergy
from src.grouper.grouper import PowerGroup


@dataclass(frozen=True)
class PropFamilyRecipe:
    """How a prop family is idiomatically sequenced, per the mined corpus."""

    family: str
    match_tokens: tuple[str, ...]
    effect_name: str
    # A name containing any of these tokens never matches, even when a
    # match_token hits — e.g. the mini-tree "tree" token must not claim
    # "TreeStar", "Mega Tree", or "Singing Tree" elements.
    exclude_tokens: tuple[str, ...] = ()
    # Alternate effect used on repeated sections (variation_seed odd) so
    # repeats vary, mirroring the Ripple/Shockwave alternation seen in the
    # corpus. None → always effect_name.
    alt_effect_name: str | None = None
    palette: tuple[str, ...] = ("#FFFFFF",)
    qualifying_labels: tuple[str, ...] = ("chorus", "drop", "hook", "climax", "build_peak")
    min_energy: int = 65
    # xLights parameter presets mined from the corpus placements. The primary
    # preset applies to effect_name; the alt preset applies to alt_effect_name
    # (empty → the alternate keeps library defaults).
    parameter_overrides: tuple[tuple[str, str], ...] = ()
    alt_parameter_overrides: tuple[tuple[str, str], ...] = ()
    # The reference packages place a section-spanning Off effect on the layer
    # beneath the beat bursts (xLights layer 2) on the group element, so the
    # props render black between bursts instead of picking up whole-house
    # bleed. Mined: snowflake Off placements are 43/58 on layer index 1;
    # arch 69/75 on layer index 1-2, spans of 12-15s tiling the sections.
    off_backdrop: bool = False
    # Optional third layer: a slower sustained motion effect rendered beneath
    # the per-beat primary (matrix idiom — the reference packages run the
    # matrices 2-3 motion layers deep under the On color layer, e.g.
    # On + Shockwave bursts + a continuous Spirals spin). Placed one segment
    # per ``secondary_beats_per_placement`` beats, solid white.
    secondary_effect_name: str | None = None
    secondary_parameter_overrides: tuple[tuple[str, str], ...] = ()
    secondary_beats_per_placement: int = 4
    # Two-layer "color over mask" composition, the dominant mega-tree idiom:
    # a section-spanning On on the upper layer with LayerMethod "2 is Unmask"
    # (517 mined placements), colored from the section theme, over the
    # recipe's motion effect on the layer directly below acting as the
    # brightness mask. Mined pairs: On-over-Spirals 269 placements,
    # On-over-Shockwave 214, On-over-Lightning 101, On-over-Pinwheel 52;
    # 72% of the tree's lit time runs 2+ layers deep.
    color_over_mask: bool = False


# Mined presets — near-unanimous across all 12 reference packages:
#
# SingleStrand chase (3.5k/4.9k placements use From Head; Color_Mix1 is the
# only per-song variable, 10-50, median 25): head-bright chase with a fading
# tail, the signature "comet" look of the reference shows.
_CHASE_FROM_HEAD: tuple[tuple[str, str], ...] = (
    ("E_NOTEBOOK_SSEFFECT_TYPE", "Chase"),
    ("E_CHOICE_Chase_Type1", "Left-Right"),
    ("E_CHOICE_Fade_Type", "From Head"),
    ("E_CHOICE_SingleStrand_Colors", "Palette"),
    ("E_SLIDER_Color_Mix1", "25"),
    ("E_SLIDER_Number_Chases", "1"),
)

# Shockwave burst (2.9k placements, fields >98% identical): center-out
# expanding ring, blended edges, single cycle.
_SHOCKWAVE_BURST: tuple[tuple[str, str], ...] = (
    ("E_NOTEBOOK_Shockwave", "Position"),
    ("E_CHECKBOX_Shockwave_Blend_Edges", "1"),
    ("E_CHECKBOX_Shockwave_Scale", "1"),
    ("E_SLIDER_Shockwave_Accel", "0"),
    ("E_SLIDER_Shockwave_CenterX", "50"),
    ("E_SLIDER_Shockwave_CenterY", "50"),
    ("E_SLIDER_Shockwave_Cycles", "1"),
    ("E_SLIDER_Shockwave_Start_Radius", "1"),
    ("E_SLIDER_Shockwave_Start_Width", "5"),
    ("E_SLIDER_Shockwave_End_Radius", "100"),
    ("E_SLIDER_Shockwave_End_Width", "35"),
)


# Candy-cane Spirals preset — mined from 736 Spirals placements on cane
# elements: flat 2D (3D=0 at 100%, unlike the mega-tree preset), single
# spiral (Count=1 at 54%), thickness 33 (67%), slow movement (1 at 56%),
# gentle rotation (+/-20 at 54%), no grow/shrink/blend (100%).
_SPIRALS_CANE: tuple[tuple[str, str], ...] = (
    ("E_SLIDER_Spirals_Count", "1"),
    ("E_SLIDER_Spirals_Rotation", "20"),
    ("E_SLIDER_Spirals_Thickness", "33"),
    ("E_TEXTCTRL_Spirals_Movement", "1"),
    ("E_CHECKBOX_Spirals_3D", "0"),
    ("E_CHECKBOX_Spirals_Blend", "0"),
    ("E_CHECKBOX_Spirals_Grow", "0"),
    ("E_CHECKBOX_Spirals_Shrink", "0"),
)


# Matrix Pinwheel preset — mined from 1.4k Pinwheel placements on matrix
# elements: New Render Method (100%), 3D Inverted (66%), 2 arms (59%),
# speed 15 (56%), thickness 30 (83%), no twist (61%).
_PINWHEEL_MATRIX: tuple[tuple[str, str], ...] = (
    ("E_CHOICE_Pinwheel_Style", "New Render Method"),
    ("E_CHOICE_Pinwheel_3D", "3D Inverted"),
    ("E_SLIDER_Pinwheel_Arms", "2"),
    ("E_SLIDER_Pinwheel_Speed", "15"),
    ("E_SLIDER_Pinwheel_Thickness", "30"),
    ("E_SLIDER_Pinwheel_Twist", "0"),
)


# Matrix Spirals preset — mined from 821 Spirals placements on matrix
# elements: single spiral (63%), 3D (59%), gentle rotation (~+/-30),
# slow movement, no grow/shrink/blend (88-97%).
_SPIRALS_MATRIX: tuple[tuple[str, str], ...] = (
    ("E_SLIDER_Spirals_Count", "1"),
    ("E_SLIDER_Spirals_Rotation", "30"),
    ("E_SLIDER_Spirals_Thickness", "30"),
    ("E_TEXTCTRL_Spirals_Movement", "1"),
    ("E_CHECKBOX_Spirals_3D", "1"),
    ("E_CHECKBOX_Spirals_Blend", "0"),
    ("E_CHECKBOX_Spirals_Grow", "0"),
    ("E_CHECKBOX_Spirals_Shrink", "0"),
)


# Mini-tree chase preset — mined from 5.3k SingleStrand placements on
# mini-tree elements: Right-Left sweep (79%), From Head fade (83%),
# chase runs across the whole group as one unit (Chase_Group_All=1 at 64%),
# Color_Mix1 50 (73%), single chase (100%).
_CHASE_MINITREE: tuple[tuple[str, str], ...] = (
    ("E_NOTEBOOK_SSEFFECT_TYPE", "Chase"),
    ("E_CHOICE_Chase_Type1", "Right-Left"),
    ("E_CHOICE_Fade_Type", "From Head"),
    ("E_CHOICE_SingleStrand_Colors", "Palette"),
    ("E_CHECKBOX_Chase_Group_All", "1"),
    ("E_SLIDER_Color_Mix1", "50"),
    ("E_SLIDER_Number_Chases", "1"),
)


# House-line Lightning preset — mined from 507 Lightning placements on
# horizontal/vertical line elements, every field unanimous (100%): thin
# unforked bolts flashing upward, used as sub-beat white accents.
_LIGHTNING_FLICKER: tuple[tuple[str, str], ...] = (
    ("E_CHOICE_Lightning_Direction", "Up"),
    ("E_CHECKBOX_ForkedLightning", "0"),
    ("E_SLIDER_Lightning_WIDTH", "1"),
    ("E_SLIDER_Lightning_TopX", "0"),
    ("E_SLIDER_Lightning_TopY", "0"),
    ("E_SLIDER_Lightning_BOTX", "0"),
    ("E_SLIDER_Number_Bolts", "10"),
    ("E_SLIDER_Number_Segments", "5"),
)


# Megatree Spirals preset — mined from 720 Spirals placements on Mega Tree
# elements: single spiral (Count=1 at 96%), no grow/shrink (96-97%), blend
# off (87%); rotation/movement/thickness vary per song, so representative
# mid-corpus values are used.
_SPIRALS_MEGATREE: tuple[tuple[str, str], ...] = (
    ("E_SLIDER_Spirals_Count", "1"),
    ("E_SLIDER_Spirals_Rotation", "140"),
    ("E_SLIDER_Spirals_Thickness", "30"),
    ("E_TEXTCTRL_Spirals_Movement", "4"),
    ("E_CHECKBOX_Spirals_3D", "1"),
    ("E_CHECKBOX_Spirals_Blend", "0"),
    ("E_CHECKBOX_Spirals_Grow", "0"),
    ("E_CHECKBOX_Spirals_Shrink", "0"),
)


CORPUS_RECIPES: tuple[PropFamilyRecipe, ...] = (
    PropFamilyRecipe(
        family="snowflake",
        match_tokens=("snowflake", "flake"),
        effect_name="Shockwave",
        alt_effect_name="Ripple",
        parameter_overrides=_SHOCKWAVE_BURST,
        off_backdrop=True,
    ),
    PropFamilyRecipe(
        family="arch",
        match_tokens=("arch",),
        effect_name="Single Strand",
        parameter_overrides=_CHASE_FROM_HEAD,
        off_backdrop=True,
    ),
    # Mega tree — mined from the same 12 packages (docs/megatree_sequencing_
    # corpus/). Time-weighted, the tree is a layered composition, not a
    # single effect: Spirals 25% / On 23% / Shader 14% / Shockwave 13% of
    # lit time, with 72% of that time 2+ layers deep. The dominant blend is
    # an On color layer unmasked by the motion effect below it
    # (color_over_mask). Shockwave/Spirals serve as the mask shapes; the
    # Shockwave preset matches the snowflake burst (>96% field agreement).
    # Off backdrop is NOT part of the megatree idiom (55/7.7k placements).
    # Tokens match "06_PROP_Mega_Tree" / "08_HERO_Mega_Tree" and member
    # names like "Mega Tree 2"; "Mega Topper" props deliberately do not
    # match — different prop family.
    PropFamilyRecipe(
        family="megatree",
        match_tokens=("megatree", "mega_tree", "mega tree"),
        effect_name="Shockwave",
        alt_effect_name="Spirals",
        parameter_overrides=_SHOCKWAVE_BURST,
        alt_parameter_overrides=_SPIRALS_MEGATREE,
        color_over_mask=True,
    ),
    # Candy canes — mined from the same 12 packages (docs/cane_sequencing_
    # corpus/, 3.0k placements on 13-16 cane elements per layout).
    # SingleStrand chase dominates (45%, median 0.55 beats, white), with
    # Spirals as the recurring alternate (24%, median 1.03 beats). Like the
    # mega tree — and unlike snowflakes/arches — the color comes from a
    # section-spanning On layer with "2 is Unmask" (459/467 On placements)
    # sitting over the motion effect: On-over-SingleStrand 217 pairs,
    # On-over-Spirals 180. Off backdrop is NOT part of the idiom
    # (29/3.0k placements, scattered).
    PropFamilyRecipe(
        family="cane",
        match_tokens=("cane", "candy"),
        effect_name="Single Strand",
        alt_effect_name="Spirals",
        parameter_overrides=_CHASE_FROM_HEAD,
        alt_parameter_overrides=_SPIRALS_CANE,
        color_over_mask=True,
    ),
    # Horizontal / vertical house lines — mined from the same 12 packages
    # (docs/horizontal_sequencing_corpus/ 1.6k placements over 10 songs,
    # docs/vertical_sequencing_corpus/ 1.8k over 9). Both families share one
    # idiom: white per-beat SingleStrand chase (70%/66%, From Head 85-89%,
    # Number_Chases 1) colored by a section-spanning On layer with
    # "2 is Unmask" (100% of 243/159 On placements), alternating with white
    # Lightning flickers (11%/18%, unanimous preset). Off placements are too
    # few/short to be the tiling-backdrop idiom (52 @ 3.3s median / 24), so
    # off_backdrop stays False.
    PropFamilyRecipe(
        family="horizontal",
        match_tokens=("horizontal", "horiz"),
        effect_name="Single Strand",
        alt_effect_name="Lightning",
        parameter_overrides=_CHASE_FROM_HEAD,
        alt_parameter_overrides=_LIGHTNING_FLICKER,
        color_over_mask=True,
    ),
    PropFamilyRecipe(
        family="vertical",
        match_tokens=("vertical", "vert"),
        effect_name="Single Strand",
        alt_effect_name="Lightning",
        parameter_overrides=_CHASE_FROM_HEAD,
        alt_parameter_overrides=_LIGHTNING_FLICKER,
        color_over_mask=True,
    ),
    # Mini trees — mined from the same 12 packages (docs/minitree_
    # sequencing_corpus/, 7.2k placements over 12 songs). White SingleStrand
    # chase dominates (73%, median 0.62 beats) with a tree-specific preset
    # (Right-Left, Chase Group All), colored by the On "2 is Unmask" layer
    # (1367/1368 On placements; On-over-SingleStrand 1077 pairs,
    # On-over-Shockwave 255). Alternate is the white Shockwave burst (3%,
    # ~1 beat, same preset as snowflakes). Exclude tokens keep the broad
    # "tree" token off tree-stars, mega trees/toppers, and singing trees
    # (whose Faces placements leaked into the mined data but are a vocal
    # idiom, not a tree idiom).
    # Matrices — mined from the same 12 packages (docs/matrix_sequencing_
    # corpus/, 11.2k placements over 12 songs, up to 13 layers deep).
    # Dominant motion effects: Shockwave 33% (0.51 beats, white), Pinwheel
    # 12% (mined preset), Spirals 7% (~2 beats, white); the color again
    # comes from an On "2 is Unmask" layer (1052/1115). The most common
    # simultaneous stacks are On over one or two motion layers
    # (On+Spirals, On+Ripple+Shockwave, On+Pinwheel), so this recipe is
    # three layers deep: On color (0) / per-beat bursts (1) / sustained
    # Spirals spin (2). Text/Pictures/Video content effects in the corpus
    # are deliberately not replicated. "lyric" is excluded so a lyrics
    # matrix keeps its dedicated word-sync treatment.
    PropFamilyRecipe(
        family="matrix",
        match_tokens=("matrix",),
        exclude_tokens=("lyric",),
        effect_name="Shockwave",
        alt_effect_name="Pinwheel",
        parameter_overrides=_SHOCKWAVE_BURST,
        alt_parameter_overrides=_PINWHEEL_MATRIX,
        secondary_effect_name="Spirals",
        secondary_parameter_overrides=_SPIRALS_MATRIX,
        color_over_mask=True,
    ),
    PropFamilyRecipe(
        family="minitree",
        match_tokens=("tree",),
        exclude_tokens=("mega", "star", "topper", "singing"),
        effect_name="Single Strand",
        alt_effect_name="Shockwave",
        parameter_overrides=_CHASE_MINITREE,
        alt_parameter_overrides=_SHOCKWAVE_BURST,
        color_over_mask=True,
    ),
)


def recipe_for_group(group: PowerGroup) -> PropFamilyRecipe | None:
    """Return the corpus recipe for a tier-6 PROP or tier-8 HERO group, or None.

    Tier 8 is included because a family's props don't always pair up into a
    tier-6 group — a layout with a single mega tree promotes it to
    ``08_HERO_Mega_Tree``, and the corpus effects were overwhelmingly placed
    on such individual model elements.

    Radial sub-groups (``prop_type == "radial"``) are never matched — they
    already have a dedicated chase-across-members placer that the corpus
    recipe must not displace.
    """
    if group.tier not in (6, 8) or group.prop_type == "radial":
        return None

    def _matches(recipe: PropFamilyRecipe, text: str) -> bool:
        return (
            any(token in text for token in recipe.match_tokens)
            and not any(token in text for token in recipe.exclude_tokens)
        )

    name = group.name.lower()
    for recipe in CORPUS_RECIPES:
        if _matches(recipe, name):
            # A generically named group ("06_PROP_Trees") can still hold a
            # different family's props ("Mega Tree 1/2") — when a majority of
            # members hit this recipe's exclude tokens, let the member-
            # majority pass below pick the right family instead.
            if group.members and recipe.exclude_tokens:
                excluded = sum(
                    1 for member in group.members
                    if any(t in member.lower() for t in recipe.exclude_tokens)
                )
                if excluded / len(group.members) > 0.5:
                    continue
            return recipe
    if group.members:
        for recipe in CORPUS_RECIPES:
            hits = sum(
                1 for member in group.members if _matches(recipe, member.lower())
            )
            if hits / len(group.members) > 0.5:
                return recipe
    return None


def section_qualifies(recipe: PropFamilyRecipe, section: SectionEnergy) -> bool:
    """Corpus recipes fire on chorus-like sections or high-energy passages."""
    label = (section.label or "").lower()
    if any(keyword in label for keyword in recipe.qualifying_labels):
        return True
    return section.energy_score >= recipe.min_energy
